version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: cesizen-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: cesizen-backend
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
